// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvI5BLkH2ZEhnlgR7tx3hYEKuxEyNHDgI',
    appId: '1:1087677710988:web:3b43c7f48cacce3ebd31a9',
    messagingSenderId: '1087677710988',
    projectId: 'ecommerceapp-55b18',
    authDomain: 'ecommerceapp-55b18.firebaseapp.com',
    storageBucket: 'ecommerceapp-55b18.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAwLC_uetTXJbE61SDfTTt90yn_wC5_jo',
    appId: '1:1087677710988:android:189aad8ba5fbda93bd31a9',
    messagingSenderId: '1087677710988',
    projectId: 'ecommerceapp-55b18',
    storageBucket: 'ecommerceapp-55b18.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNvF44Vuk0QgtkB7jtBbio03ThXj0xihM',
    appId: '1:1087677710988:ios:1f8945daf46afb4bbd31a9',
    messagingSenderId: '1087677710988',
    projectId: 'ecommerceapp-55b18',
    storageBucket: 'ecommerceapp-55b18.appspot.com',
    androidClientId: '1087677710988-hsq71cl205s81kl6u6cdvrjfo3u2opgn.apps.googleusercontent.com',
    iosClientId: '1087677710988-57th70a7qiipeu1tpla65mqehfvs86oh.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

}